### ISSUE TITLE
アプリ全体で使える教科フォルダのデータベースシステム作成とデータの取得

### ISSUE THREAD

**Issue by Dai1678** [TaigaNatto/MatoMemo#50]
GroupEditActivityで作った教科フォルダをStartListActivity、MatoMemoListActivityで共有できるように
データベースのシステム作って組み合わせましょう。

@Kawaguchi410 
GroupEditActivityのデータ管理方法確認したいです

**Comment by Kawaguchi410** [comment]
タップされたグループの名前を、MatoMemoListActivityにintentで送る処理を実装しました。パスは 「folder」 です。
